### ISSUE TITLE
Specify Python version in the Readme.md

### ISSUE THREAD

**Issue by Jujie-YANG** [TJU-DRL-LAB/AI-Optimizer#1]
I am not sure whether the python version matters in deep reinforcement learning. As I know, probably python 3.7 is the most stable and good used version for machine learning. Could you please specify what version you guys used and add this information to the Readme file? Many thanks.

**Comment by Phil610351** [comment]
自己论文的代码一个都没开源，，，，

**Comment by Jujie-YANG** [comment]
> 自己论文的代码一个都没开源，，，，

Thanks so much for your replying! Is it not open source? I am so sorry. I thought it was open source. Several days ago, I just searched for a public project I can contribute to on Github. Then I found this project in terms of deep reinforcement learning quite attractive and I would like to contribute to it because I saw the Readme file says AI-Optimizer is still under development and welcome contribution.

**Comment by Jujie-YANG** [comment]
> 自己论文的代码一个都没开源，，，，

哇 我突然发现 你的头像跟Jack Cui的一模一样 吓我一跳 🤣🤣

**Comment by Phil610351** [comment]
发错地方了，想说马亿那屌丝呢，代码也不开源


---Original---
From: ***@***.***&gt;
Date: Wed, Mar 23, 2022 19:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TJU-DRL-LAB/AI-Optimizer] Specify Python version in the Readme.md (Issue #1)




  
自己论文的代码一个都没开源，，，，
  
哇 我突然发现 你的头像跟Jack Cui的一模一样 吓我一跳 🤣🤣

**Comment by Jujie-YANG** [comment]
> 发错地方了，想说马亿那屌丝呢，代码也不开源
蛤？啥意思？你指的是这个project没开源嘛 还是指亿兄的其它project？

**Comment by Phil610351** [comment]
你们都是大佬

**Comment by Jujie-YANG** [comment]
> 你们都是大佬

别误会哥 我只是个菜鸡路人 我才大一 你们都是我虚心请教的对象～ 我只是想 如果有机会 通过这个project学习一下deep reinforecement learning 然后完成一下我这学期的期末作业而已🤣🤣🤣

**Comment by mamengyiyi** [comment]
> I am not sure whether the python version matters in deep reinforcement learning. As I know, probably python 3.7 is the most stable and good used version for machine learning. Could you please specify what version you guys used and add this information to the Readme file? Many thanks.

Hi, we are working on improving the codes and corresponding instructions in readme. Thanks for your attention!

**Comment by Jujie-YANG** [comment]
> > I am not sure whether the python version matters in deep reinforcement learning. As I know, probably python 3.7 is the most stable and good used version for machine learning. Could you please specify what version you guys used and add this information to the Readme file? Many thanks.
> 
> Hi, we are working on improving the codes and corresponding instructions in readme. Thanks for your attention!

Thanks so much for your replying! I really hope I can contribute something to this project. Many thanks.
